# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#Serving
port: 1000
url: "https://berkhaneminsoy.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: "" # the subpath of your site, e.g. /blog
domain: berkhaneminsoy.github.io

locale: "en-US"
title: jekyll minima master fork build
description: > # this means to ignore newlines until "show_excerpts:" It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  berkhan eminsoy. architectural designer born in Istanbul, bred in U.S. All things architecture and ancillary.
copyright: © 2021 Berkhan Eminsoy.
github: [metadata]

#Site Author
author:
  name: berkhan 'b' eminsoy
  email: beminsoy@gmail.com
  avatar: 
  location: 
  bio: > 
    architectural designer **born** in *Istanbul*, **trained** in the *US*.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

theme: minima
#remote-theme: jeklly/minima

show_excerpts: true # set to true to show excerpts on the homepage
excerpt_separator: <!-- excerpt-end -->

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: "classic_+"

  # generate social links in footer
  social_links:
    twitter: BerkhanEminsoy
    github:  BerkhanEminsoy
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# Handling Reading

# Excludes
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Includes
# refer to; https://github.com/jekyll/jekyll/issues/920#issuecomment-63093764
include: 
  - _pages
#  - _collections

# Collections
# collections_dir: _collections
collections:
  projects:
    output: true
    institution: N/A
    time: N/A

# Header Pages
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - index.html
#  - _pages/work.md
  - _pages/log.md
  - _pages/about.md
#  - _pages/history.md

# Plugins (previously gems)
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme
 - jekyll-include-cache
 - jekyll-archives
 - jekyll_figure

# Figures
# settings for the jekyll_figure plug-in by #https://github.com/lmullen/jekyll_figure
figures:
  dir: assets/img
  enumerate: true

# Defaults
# set defaults for collections & other
# refer to; https://stackoverflow.com/questions/62104684/managing-jekyll-pages-in-folders-on-github-pages
defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      permalink: /:basename/ # make URL of pages in the folder _pages as on the root.
  - scope:
      path: "_collections"
    values:
      permalink: /:collection/:title/ # make URL of pages in the folder _pages as on the root.
